### ISSUE TITLE
Deploy data set on actual devices (R-Pi)

### ISSUE THREAD

**Issue by razvand** [unibuc-cs/IoT-application-set#11]
Deploy data set applications on actual devices such as Raspberry-Pi.

**Comment by andreia-oca** [comment]
The dataset has now Dockerfiles built for armv7 (see [PR 27](https://github.com/unibuc-cs/IoT-application-set/pull/27)).

The dataset can now be deployed on Raspberry Pi with `docker-compose up -d`. 

Raspberry Pi - Prerequisites:
- at least 1Gb of RAM
- at least 10 Gb of storage (for Raspbian and Docker images) 
- `docker` and `docker-compose` installed
